# Generated by Django 3.2.7 on 2021-09-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
